sudo: required
services:
  - docker

before_install:
  - docker build -t sarvang00/docker-react-prod-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sarvang00/docker-react-prod-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-display"
  env: "Dockerdisplay-env"
  bucket_name: "elasticbeanstalk-ap-south-1-585360292342"
  bucket_path: "docker-display"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY